# Generated by Django 4.1.7 on 2024-07-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntitiesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorium', models.CharField(max_length=255, verbose_name='Auditorium')),
                ('program_name', models.CharField(max_length=255, verbose_name='Program Name')),
                ('date_time', models.CharField(max_length=255, verbose_name='Date and Time')),
                ('artists', models.JSONField(blank=True, default=list, verbose_name='Artists')),
            ],
            options={
                'verbose_name': 'entity master',
                'verbose_name_plural': 'entities master',
                'db_table': 'entities_master',
            },
        ),
    ]
